import React from "react";
import Navbar from "../../components/navbar";
import Head from "next/head";

const ForgottenLand = () => {
  return (
    <div>
      <Head>
        <title>Forgotten Land</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1 class="font-medium leading-tight text-5xl mt-0 mb-2 text-blue-600 text-center mt-5 mb-10">
        Forgotten Land
      </h1>
      <div className="container">
        <img
          id="story-image-small"
          className="w-[520px] h-[520px] ml-[220px]"
          src="/images/Forgotten Land/IMG_8481.jpg"
        />
        <p className="text text-center m-5">
          The Pakistan’s former tribal areas remained the epicenter of the so
          called “War on Terror” The region plunged into a decade long violence.
          The US former president Obama refer to the region as “the most
          dangerous place in the world.” When he started nonstop drone strikes
          and Pushed Pakistani military into carrying multiple military
          operations killing and displacing thousands of the people from the
          region. The region until 2018 was ruled by colonial law called
          Frontier crime regulation (FCR).
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Forgotten Land/111.jpg"
        />
        <p className="text text-center mb-10 ml-5 mr-5">
          Kurram is one of the seven districts of former tribal areas. It shares
          border with three Afghan provinces, Nangrahar in its North, Paktia and
          Khost in its west. The district was home to scores of Mujaheedin
          training camps during cold war. When US invaded Afghanistan. Many
          Al-Qaida fighters escaped from bombing over Torabora caves located in
          Spighar range.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Forgotten Land/IMG_9372.jpg"
        />
        <p className="text text-center mb-10 mr-5 ml-5">
          The areas is inhabited by several Pashtun tribes. Turi is major tribe
          of the district and it is the only Pashtun tribe following shia faith.
          The region has long history of sectarian conflicts dating back to the
          era when the region was part of Afghanistan. The tribe was persecuted
          by Afghan kings for its faith and to extract revenue from the tribe
          living on both sides of the river Kurram.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Forgotten Land/IMG_9336.jpg"
        />
        <p className="text text-center mb-10 mr-5 ml-5">
          In 2007 when Taliban started resurgence in Afghanistan. The Haqqani
          Taliban envisaged to engage US and NATO forces allover Afghanistan. As
          Kurram shares border with three Afghan province and considered to be
          the closest Pakistani town to Kabul. Haqqani Taliban started making
          inroad in the Kurram, whoever Turis being shia were feared
          conservative Deobandi Sunni Taliban and they stopped Taliban from
          carrying cross border attacks in Afghanistan.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Forgotten Land/IMG_6610.jpg"
        />
        <p className="text text-center mb-10 mr-5 ml-5">
          In response Taliban ambushed Turi villages in Kurram in 2007 and
          closed the only road which connects it with rest of Pakistan. Taliban
          put Turis under siege for year and continued attacks on the villages
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Forgotten Land/DSC00320.jpg"
        />
        <p className="text text-center mb-10 mr-5 ml-5">
          Turis mobilized its forces and fought against Taliban for years,
          completely cut from the rest of the country. There was food and
          medicine shortages. The region was not covered by local and
          international media. The school and colleges remained closed. Students
          used to travel through Afghanistan to their universities in Peshawar.
          Kurram has highest literacy rate in the tribal districts but the
          generation which grew up during these years was forcefully militarized
          by the state as the state deliberately withheld its writ.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Forgotten Land/Photo0870.jpg"
        />
        <p className="text text-center mb-10 mr-5 ml-5">
          According to The News article in 2021 from March to September 71
          suicides were recorded in Kurram, highest in the Pakistan. In 2018
          Pakistani government merged tribal areas of Pakistan with Khyber
          Pakhtunkhwa province after a successful youth lead rights based
          movement called Pashtun Tahafuz/protection Movement (PTM).
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Forgotten Land/IMG_9425.jpg"
        />
        <p className="text text-center mb-10 mr-5 ml-5">
          The merger failed to mainstream the region to bring it par with rest
          of the Pakistan as the region is one of the poorest place in the
          country. Most of the people are dependent on subsistence farming
          remittances from abroad. Many of the youth have migrated to gulf,
          Australia and Iraq.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Forgotten Land/IMG_6520.jpg"
        />
        <p className="text text-center mb-10 mr-5 ml-5">
          The militarized and unemployed youth was recruited by Iran to fight on
          behalf of Assad regime in the Syria against ISIS.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Forgotten Land/DSC00290.jpg"
        />
        <p className="text text-center mb-10 mr-5 ml-5">
          However the violence in the region especially among Pashtuns are still
          analyzed through 19th and 20th century colonial orientalist
          stereotyping of Pashtuns. The colonial anthropologists viewed Pashtun
          in binary e.g brave and honorable or treacherous scoundrels. The
          colonial literature has depicted Pashtuns as warriors or semi savages.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Forgotten Land/IMG_6275.jpg"
        />
        <p className="text text-center mb-10 mr-5 ml-5">
          The postcolonial state of Pakistan inherited the colonial knowledge
          and its quest for strategic narrative in Afghanistan has been
          exploiting the colonial orientalist tropes. During Taliban insurgency,
          Pakistani government and scholars termed Taliban insurgency as Pashtun
          phenomenon.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Forgotten Land/IMG_8134.jpg"
        />
        <p className="text text-center mb-10 mr-5 ml-5">
          When Pakistan announced military operation zarb e azab in 2014 in
          Waziristan. Thousands of locals were displaced from their houses,
          leaving everything behind. However in the cities they were not
          welcomed by Pakistanis as they equated Pashtun with Taliban despite
          being the most affected by Taliban.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image-small"
          className="w-[420px] h-[520px] ml-[280px] mr-[80px] mt-[80px] mb-5"
          src="/images/Forgotten Land/IMG_3998.jpg"
        />
        <p className="text text-center mb-10 mr-5 ml-5">
          Pashtuns were harassed and are still harassed whenever there is a
          blast in the city. The harassment of Pashtuns came to the surface when
          a peaceful nonviolent, youth lead Pashtun Tahfuz/Protection Movement
          (PTM). Many of the activist of the movement were either arrested or
          killed for example Ali Wazir Member of Parliament from South
          Waziristan and leader of PTM whom 15 family members were killed by
          Taliban has been in jail for last one year for his protest against
          violence in tribal areas. On 27th of May Pakistan has announced
          officially that they are having peace talks with Taliban.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image-small"
          className="w-[420px] h-[520px] ml-[280px] mr-[80px] mt-[80px] mb-5"
          src="/images/Forgotten Land/IMG_6466.jpg"
        />
        <p className="text text-center mb-10 mr-5 ml-5">
          However Taliban are demanding to reverse the merger of tribal areas of
          Pakistan as The region tribe before colonial area self-governed
          themselves through tribal traditions and customs. The colonial
          administration in British India started governing tribal regions
          indirectly through bifurcated customary law called Frontier Crime
          Regulation (FCR). The law instrumental to govern regions which were
          expensive to govern and extract taxes through revenue. This law was
          more coercive as it instrumentalised the most patriarchal and
          subversive customs of the tribes and governed the local through their
          own customary elders and militias by promulgating collective
          punishment rules.
        </p>
      </div>
    </div>
  );
};

export default ForgottenLand;
