import React from "react";
import Navbar from "../../components/navbar";
import Head from "next/head";

const RawalpindiUnderSeige = () => {
  return (
    <div>
      <Head>
        <title>Rawalpindi Under Seige</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1 className="font-medium leading-tight text-5xl mt-0 mb-2 text-blue-600 text-center mt-5 mb-10">
        Rawalpindi Under Seige
      </h1>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/const.png"
        />
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/IMG_0227.jpg"
        />
        <p className="text italic text-center mb-10">
          Dadhocha, Bharwala, Khanpur, Dhadhar Najaar, Mohra Wains villages
          close to Rawat industrial areais in Rawalpindi .
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/IMG_3472.jpg"
        />
        <p className="text italic text-center mb-10">
          On January 3rd, 2021, the residents of the village Dadhocha gathered
          to protest against dispossession of the villagers from their village.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/IMG_3486.jpg"
        />
        <p className="text italic text-center mb-10">
          Local farmers and villagers said that the Punjab government and
          district administration had commenced construction of the dam without
          any settlement with the indigenous inhabitants or a resettlement plan
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/protest.png"
        />
        <p className="text italic text-center mb-10 m-5">
          They were being offered a pitiful Rs. 5000 per marla for their
          agricultural land which was a fraction of their actual market value
          while the same agricultural land in the area under DHA’s possession
          was being valued by the latter at nearly 80 times that price.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/dam.png"
        />
        <p className="text italic text-center mb-10 m-5">
          The locals are being dispossessed of lands that were even beyond the
          limits of those demarcated for the dam, ostensibly for commercial
          purposes. Some residents spoke of how the adjacent DHA Valley had also
          occupied their ancestral lands despite the fact that a court had
          already ruled that it belonged to the villagers. They said that this
          occupation by DHA was preventing them from resettling their households
          in the nearby location.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/dam4.jpg"
        />
        <p className="text italic text-center mb-10 m-5">
          The locals are not against dam construction to benefit Rawalpindi’s
          residents but said that it should not be done at the cost of the
          forced displacement of local inhabitants, who should instead be justly
          compensated and resettled within the area. The residents were not even
          sure if they could now bury their deceased loved ones in the local
          graveyard as that too would soon become submerged following the dam’s
          construction.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/pot2.png"
        />
        <p className="text italic text-center mb-10 m-5">
          The residents of the affected villages are walking to construction
          site.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/fwo.jpg"
        />
        <p className="text italic text-center mb-10 m-5">
          FWO had set up its camp. The locals called on-site officers to abide
          by court orders and not begin construction of the dam without reaching
          a just consensus-based settlement with the local residents.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/IMG_0159.jpg"
        />
        <p className="text italic text-center mb-10 m-5">
          The residents of the affected villages forced FWO to stop work on the
          site.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/prot2.jpg"
        />
        <p className="text italic text-center mb-10 m-5">
          Residents of the village are having conversation with DC Rawalpindi.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image-small"
          className="w-[620px] h-[620px] ml-[180px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/prot3.jpg"
        />
        <p className="text italic text-center mb-10 m-5">
          The protestors vowed that if the construction doesn't stop they will
          organise a march to Islamabad.
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/bikes.jpg"
        />
        <p className="text italic text-center mb-10 m-5">
          The construction is on some distance from the villages, so many people
          brought their bikes
        </p>
      </div>
      <div className="container">
        <img
          id="story-image-small"
          className="w-[620px] h-[620px] ml-[180px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/IMG_3554.jpg"
        />
        <p className="text italic text-center mb-10 m-5">
          Locals have made watch towers to protect their communal lands from
          landgrabers
        </p>
      </div>
      <div className="container">
        <img
          id="story-image"
          className="w-[820px] h-auto ml-[80px] mr-[80px] mt-[80px] mb-5"
          src="/images/Rawalpindi Under Seige/dam5.png.jpg"
        />
        <p className="text italic text-center mb-10 m-5">
          View of construction site of the Dadhocha dam
        </p>
      </div>
    </div>
  );
};

export default RawalpindiUnderSeige;
