import Head from "next/head";
import styles from "../styles/Home.module.css";
import Gallery from "./gallery";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hassan Turi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Gallery />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
